README.md

Add presentations to README

---

.travis.yml
examples/Polynomial_Optimization.ipynb
src/SumOfSquares.jl
src/constraint.jl
src/matpoly.jl
src/variable.jl
test/constraint.jl
test/extract_domain_polyopt.jl
test/runtests.jl
test/variable.jl

Goes with https://github.com/JuliaOpt/PolyJuMP.jl/pull/18/

Move some methods to PolyJuMP

---

src/SumOfSquares.jl
src/constraint.jl
src/variable.jl
test/constraint.jl
test/sosdemo5.jl
test/sosdemo6.jl
test/switchedsystems.jl
test/variable.jl

Update for https://github.com/JuliaOpt/PolyJuMP.jl/pull/22

Update for polynomial basis

---

src/variable.jl
test/options_pricing.jl
test/sdsos_example.jl

Requires https://github.com/JuliaOpt/JuMP.jl/pull/1362 to be merged for tests to pass as SOC constraints need to be bridged with CSDP

Implement SDSOS

---

README.md
REQUIRE

Add comment about version of JuMP supported

---

.travis.yml
docs/Project.toml
src/constraint.jl
test/extract_domain_polyopt.jl
test/options_pricing.jl
test/sosdemo5.jl
test/sosdemo6.jl

Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/49

Provide access to lagrangian multipliers

---

.travis.yml
REQUIRE
appveyor.yml
src/SumOfSquares.jl
src/certificate.jl
src/constraint.jl
src/sosdec.jl
test/options_pricing.jl
test/runtests.jl

⬆️ Drop Julia v0.6

---

.travis.yml

Closes #55.
(this is an attempt based on [this similar problem](https://github.com/JuliaLang/Pkg.jl/issues/821), i don't know if it fixes it. . .)

Update travis docs build script

---

test/options_pricing.jl
test/segfault.jl

Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/48

✅ Reenable options_princing.jl

---

src/constraint.jl
src/variable.jl
test/variable.jl

See https://github.com/JuliaOpt/SumOfSquares.jl/issues/66

♻️ Replace createpoly by JuMP.add_variable

---

.travis.yml
REQUIRE
examples/Sum-of-Squares Matrices.ipynb
src/SumOfSquares.jl
src/attributes.jl
src/constraint.jl
src/diagonally_dominant.jl
src/diagonally_dominant_bridge.jl
src/matpoly.jl
src/psd2x2_bridge.jl
src/scaled_diagonally_dominant_bridge.jl
src/sos_polynomial.jl
src/sos_polynomial_bridge.jl
src/sos_polynomial_in_semialgebraic_set_bridge.jl
src/utilities.jl
src/variable.jl
test/constraint.jl
test/dsos.jl
test/extract_domain_polyopt.jl
test/options_pricing.jl
test/sdsos_example.jl
test/sdsos_simple.jl
test/simplematrixsos.jl
test/solvers.jl
test/sosdemo1.jl
test/sosdemo3.jl
test/sosdemo4.jl
test/sosdemo6.jl
test/sosdemo7.jl
test/variable.jl

Requires https://github.com/JuliaOpt/PolyJuMP.jl/pull/35
~~Requires https://github.com/JuliaOpt/JuMP.jl/pull/1791~~
Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/669
~~Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/610~~
~~Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/634~~
~~Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/642~~
~~Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/643~~
~~Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/644~~
~~Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/645~~
~~Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/646~~
~~Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/648~~
Closes …

♻️ Refactor constraints with bridges

---

.travis.yml
REQUIRE
src/constraint.jl
src/scaled_diagonally_dominant_bridge.jl
test/constraint.jl

See https://github.com/JuliaOpt/PolyJuMP.jl/pull/37

Implement printing

---

src/matpoly.jl
test/REQUIRE
test/matpoly.jl

Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/75

Fix MatPoly + constant

---

examples/goldsteinprice.jl

Update goldsteinprice example for JuMP v0.19

---

docs/src/index.md

I'll try to update the other examples as well.

Update docs example for JuMP v0.19

---

examples/goldsteinprice.jl

Also deleted the `using JuMP` line as SumOfSquares reexports JuMP

Update goldsteinprice example for MosekTools

---

examples/Polynomial_Optimization.ipynb

FIxes #77 
There was an empty code cell at the end of the notebook which I have deleted. In case this was intentional please let me know and I'll add it again.

Update Polynomial Optimization notebook for JuMP 0.19

---

src/variable.jl
test/variable.jl

Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/87

Fix container of SDSOSPoly

---

Project.toml
REQUIRE
test/REQUIRE

See https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677/142

Replace REQUIRE files by Project.toml

---

src/SumOfSquares.jl
src/attributes.jl
src/copositive_inner.jl
src/copositive_inner_variable_bridge.jl
src/generic_variable_bridge.jl
src/psd2x2_variable_bridge.jl
src/scaled_diagonally_dominant_variable_bridge.jl
src/sos_polynomial_bridge.jl
src/sos_polynomial_in_semialgebraic_set_bridge.jl
test/Mock/BPT12e399.jl
test/Mock/bivariate_quadratic.jl
test/Mock/concave_then_convex_cubic.jl
test/Mock/lyapunov_switched_system.jl
test/Tests/bivariate_quadratic.jl
test/Tests/utilities.jl

Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/104

Add PSD2x2 variable bridge

---

src/SumOfSquares.jl

This allows to do
```julia
using SumOfSquares
@set x >= 1
```
assuming `x` is defined, without the need to do `using SemialgebraicSets`.

Reexport SemialgebraicSets

---

README.md

cc @tweisser @chriscoey @lkapelevich @juan-pablo-vielma

Add JuliaCon presentation

---

src/Certificate.jl
src/SumOfSquares.jl
src/constraint.jl
src/newton_polytope.jl
src/rand.jl
src/sos_polynomial.jl
src/sos_polynomial_bridge.jl
src/sos_polynomial_in_semialgebraic_set_bridge.jl
test/Tests/bivariate_quadratic.jl
test/Tests/term.jl
test/Tests/term_fixed.jl
test/certificate.jl

This is one of the result of our collaboration with @tweisser at LANL

Add certificate abstraction

---

src/Bridges/Variable/copositive_inner.jl
src/Bridges/Variable/scaled_diagonally_dominant.jl
src/sos_polynomial.jl
test/Mock/BPT12e399.jl
test/Mock/chebyshev.jl
test/Mock/choi.jl
test/Mock/concave_then_convex_cubic.jl
test/Mock/horn.jl
test/Mock/lyapunov_switched_system.jl
test/Mock/maxcut.jl
test/Mock/motzkin.jl
test/Mock/quadratic.jl
test/Mock/quartic_comparison.jl
test/Mock/sosdemo10.jl
test/Mock/sosdemo9.jl
test/Mock/term.jl
test/Mock/term_fixed.jl
test/Mock/utilities.jl
test/Tests/horn.jl
test/Tests/maxcut.jl

I found that `test/Solvers/solver_tests.jl` was failing because of the copy, this should reduce the difference of coverage with `test/Mock/mock_tests.jl`.

Fixes found by adding tests with cache

---

src/Bridges/Constraint/sos_polynomial.jl
src/Bridges/Constraint/sos_polynomial_in_semialgebraic_set.jl
src/Certificate.jl
src/sos_polynomial.jl

Add function add_gram_matrix

---

src/Bridges/Constraint/sos_polynomial.jl
test/Mock/BPT12e399.jl
test/Mock/quartic_ideal.jl
test/Solvers/csdp_tests.jl
test/Solvers/mosek_tests.jl
test/Solvers/proxsdp_tests.jl
test/Tests/BPT12e399.jl
test/Tests/quartic_ideal.jl

Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/139

Update BPT example

---

src/Certificate/csp/ChordalExtensionGraph.jl

(Sorry for working on master. )
This seems to fix the issue I reported earlier. 
Somehow inactive nodes must have been included in the candidate clique...

fix not properly added maximal cliques

---

examples/chordal_sparsity_with_domain.jl
examples/sparse_polynomials.jl
src/constraint.jl
test/Tests/rearrangement.jl
test/Tests/univariate_sum.jl
test/constraint.jl

We discussed with @tweisser and think it's a better keyword name. Let's rename before we make a release !

Rename sparse -> sparsity

---

Project.toml
examples/Noncommutative variables.ipynb

See https://github.com/JuliaOpt/SumOfSquares.jl/issues/15
Requires DynamicPolynomials v0.3.1

Add noncommutative example

---

Project.toml
examples/Noncommutative variables.ipynb
examples/Project.toml
src/Certificate/newton_polytope.jl
test/Tests/simple_matrix.jl
test/certificate.jl
test/runtests.jl

Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/7

Implement newton chip

---

CITATION.bib
README.md

Add the bibtex entry for JuliaCon presentation and reference the `CITATION.bib` file from the README.
Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/157

Add JuliaCon presentation bibtex entry

---

src/Certificate/Certificate.jl
src/constraint.jl
test/Mock/mock_tests.jl
test/Mock/quartic_constant.jl
test/Tests/Tests.jl
test/Tests/quartic_constant.jl

Closes https://github.com/JuliaOpt/SumOfSquares.jl/issues/159

Add support for given polynomial basis

---

examples/Symmetry reduction.jl

Update example for https://github.com/kalmarek/SymbolicWedderburn.jl/pull/15

Update to symmetry_adapted_basis branch

---

examples/Even reduction.jl
examples/Symmetry reduction.jl

Update needed now that https://github.com/kalmarek/SymbolicWedderburn.jl/pull/27/ is rebased on top of https://github.com/kalmarek/SymbolicWedderburn.jl/pull/25/

Rework examples to work with action characters

---

docs/src/tutorials/Symmetry/even_reduction.jl
src/Certificate/Symmetry/Symmetry.jl
src/Certificate/Symmetry/block_diag.jl
src/Certificate/Symmetry/utils.jl
src/Certificate/Symmetry/wedderburn.jl

This would have caught https://github.com/kalmarek/SymbolicWedderburn.jl/issues/35

Check that induced representation matrices are orthogonal

---

docs/src/tutorials/Polynomial Optimization/polynomial_optimization.jl

Use the tolerances added in https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl/pull/488 to find the solution in the example.

Fix HomotopyContinuation example

---

docs/src/constraints.md
docs/src/tutorials/Symmetry/permutation_symmetry.jl
src/Certificate/Certificate.jl
src/constraint.jl
test/Tests/chebyshev.jl
test/Tests/rearrangement.jl
test/equalitypolyconstr.jl

Closes https://github.com/jump-dev/SumOfSquares.jl/issues/219
Closes https://github.com/jump-dev/SumOfSquares.jl/issues/167

Change interpretation and default maxdegree

---

.github/workflows/ci.yml
Project.toml
docs/src/constraints.md
docs/src/variables.md
src/constraint.jl
test/solvers.jl

Part of https://github.com/jump-dev/JuMP.jl/issues/2564
Closes https://github.com/jump-dev/SumOfSquares.jl/pull/234
Closes https://github.com/jump-dev/SumOfSquares.jl/pull/235
Closes https://github.com/jump-dev/SumOfSquares.jl/pull/236
Closes https://github.com/jump-dev/SumOfSquares.jl/pull/237

Update to MOI v1 and JuMP v0.23

---

docs/src/tutorials/Extension/certificate.jl
docs/src/tutorials/Extension/hypercube.jl
docs/src/tutorials/Getting started/circle.jl
src/Bridges/Constraint/sos_polynomial.jl
src/Certificate/Certificate.jl
src/Certificate/Sparsity/ideal.jl
test/certificate.jl

Closes https://github.com/jump-dev/SumOfSquares.jl/issues/106

Fix constraint with less variables than variety

---

src/Certificate/Symmetry/wedderburn.jl

It allows using `_gram_basis` which was helpful when debugging https://github.com/jump-dev/SumOfSquares.jl/pull/245

Refactor Symmetry.gram_basis

---

Project.toml

Needs new patch releases of:
Closes #247

Add support for JuMP 1.0

---

docs/Project.toml
docs/src/tutorials/Extension/typed.jl
src/gram_matrix.jl
src/sosdec.jl
test/simplepolysos.jl

There are currently 3 issues blocking this:

Add example on using TypedPolynomials

---

docs/src/tutorials/Polynomial Optimization/polynomial_optimization.jl

Two minor corrections:
- I corrected a broken link to the explanation of Registered functions (was to some previous concrete version of Jump, and it did not work, I redirected it to the stable version).
- I corrected the statement about the polynomial optimization (minimization) providing a bound. It was "largest upper" bound, I changed to "largest lower" bound.

Two minor corrections in the docs for SumOfSquares.

---

src/Certificate/Symmetry/wedderburn.jl
src/sosdec.jl
test/ceg_test.jl
test/symmetry.jl

Follows suggestions from VSCode

size -> axes

---

docs/src/tutorials/Systems and Control/quadrotor.jl

Preview https://jump-dev.github.io/SumOfSquares.jl/previews/PR274

Add polar approach to quadrotor tutorial

---

src/constraint.jl

Needed in order to work with https://github.com/jump-dev/PolyJuMP.jl/pull/77

Fix printing with latest version of JuMP

---

docs/src/tutorials/Getting started/sum-of-squares_matrices.jl
src/Certificate/ideal.jl
src/Certificate/newton_polytope.jl
src/Certificate/preorder.jl
src/rand.jl
test/Tests/quadratic.jl
test/Tests/term.jl
test/Tests/term_fixed.jl
test/certificate.jl
test/sparsity.jl

Preview https://jump-dev.github.io/SumOfSquares.jl/previews/PR287

Refactor Newton postfilter

---

src/Certificate/newton_polytope.jl
test/certificate.jl

Preview https://jump-dev.github.io/SumOfSquares.jl/previews/PR288

Post filter for putinar

---

docs/src/constraints.md
docs/src/variables.md

Quite easy with `doctest(SumOfSquares, fix = true)`

Update doctests for Julia v1.9

---

test/constraint.jl

JuMP broke this feature of SumOfSquares but because it was only tested by the tutorials, it was not noticed in https://github.com/jump-dev/JuMP.jl/pull/3435
I guess that's a good reason why we shouldn't have features only tested by the tutorials

Add test for Complex bridges

---

src/Certificate/Symmetry/block_diag.jl
test/symmetry.jl

Fixes the error reported in https://github.com/blegat/CondensedMatterSOS.jl/pull/33#issue-1899065309

Fix simultaneous block diagonalization for Complex

---

docs/src/tutorials/Systems and Control/barrier_certificate.jl

Improves the clarity of example

Create separate plots for X₀, Xᵤ, and B = 0

---

docs/src/tutorials/Polynomial Optimization/bilinear.jl
docs/src/tutorials/Polynomial Optimization/ellipsoid.jl
docs/src/tutorials/Polynomial Optimization/min_univariate.jl

Preview https://jump-dev.github.io/SumOfSquares.jl/previews/PR329

Add exterior of ellipsoid example

---

docs/src/tutorials/Getting started/dualization.jl

Preview https://jump-dev.github.io/SumOfSquares.jl/previews/PR333

Add tutorial on Dualization

---

docs/src/sumofsquares.md

Preview https://jump-dev.github.io/SumOfSquares.jl/previews/PR339
Closes https://github.com/jump-dev/SumOfSquares.jl/issues/338

Fix link to Motzkin example

---

docs/src/constraints.md

Closes https://github.com/jump-dev/SumOfSquares.jl/pull/343

Add missing docstring

---

src/Bridges/Constraint/diagonally_dominant.jl
src/Bridges/Constraint/empty.jl
src/Bridges/Constraint/psd2x2.jl
src/Bridges/Constraint/scaled_diagonally_dominant.jl
src/Bridges/Constraint/sos_polynomial.jl
src/Bridges/Variable/copositive_inner.jl
src/Bridges/Variable/psd2x2.jl
src/Bridges/Variable/scaled_diagonally_dominant.jl
src/build_matrix.jl

We made that change in MOI but I forgot to make it here as well

DataType -> Type

---

docs/src/tutorials/Extension/typed.jl

It would have caught some error on https://github.com/jump-dev/SumOfSquares.jl/pull/296

Add test for typed tutorial

---

test/Bridges/Variable/kernel.jl

Test variable substitution for KernelBridge

---

src/SumOfSquares.jl
src/constraints.jl
test/Mock/mock_tests.jl
test/Mock/quadratic.jl
test/Solvers/Manifest.toml
test/Solvers/generate.jl
test/Tests/utilities.jl

Fix quadratic tests

---

docs/src/constraints.md
docs/src/variables.md
src/Certificate/Symmetry/block_diag.jl
test/symmetry.jl

See https://github.com/jump-dev/SumOfSquares.jl/issues/381

[Symmetry] Fix sign scaling in ordered_block_diag

---

src/Certificate/Symmetry/wedderburn.jl

This is a fix for the minor bug mentioned in issue #387 (does not fix the issue itself)

Fix minor bug in error message #387

---

Project.toml
docs/src/reference/certificate.md
docs/src/tutorials/Sparsity/term_sparsity.jl
src/Certificate/Sparsity/ChordalExtensionGraph.jl
test/ceg_test.jl

I have a library [CliqueTrees.jl](https://github.com/AlgebraicJulia/CliqueTrees.jl/tree/main) with a fast implementation of the minimum fill ordering heuristic. Here are some benchmarks.
```julia
using BenchmarkTools
using MatrixMarket
using SuiteSparseMatrixCollection
using SparseArrays
using SumOfSquares.Certificate.Sparsity: ChordalExtensionGraph as CEG
ssmc = ssmc_db()
name = "bcsstk13"
matrix = mmread(joinpath(fetch_ssmc(ssmc[ssmc.name .== name, :], format="MM")[1], "$(name).mtx"));
G = CEG.LabelledGraph{Int}()
for j in axes(matrix, 2)
CEG.add_node!(G, j)
for i in @view rowvals(matrix)[nzrange(matrix, j)]
if i < j
CEG.add_edge!(G, i, j)
end
end
end
```
**current implementation**
```julia
julia> @benchmark CEG.completion(G, CEG.ChordalCompletion())
BenchmarkTools.Trial: 1 sample with …
```

Fast implementation of the minimum fill ordering heuristic.

---

src/Certificate/newton_polytope.jl

Part of https://github.com/jump-dev/SumOfSquares.jl/pull/391

Refactor Newton Polytope to avoid 3-factor products
