- src/variable.jl
The ordering has been moved from row by row upper triangular to column by column upper triangular from MPB to MOI. SymMatrix now uses column by column upper triangular on master (see https://github.com/JuliaAlgebra/MultivariateMoments.jl/commit/58006b0bad979f4b86093397f1968dddfaa3396c) so using master SumOfSquares.jl and master MultivariateMoments.jl currently fails.
With the change of this PR, we access the SymMatrix using cartesian indexing the the behavior does not depend on the order the entries are stored in the SymMatrix which is safer.
> Fix psd variable ordering

- .travis.yml
- examples/Polynomial_Optimization.ipynb
- src/SumOfSquares.jl
- src/constraint.jl
- src/matpoly.jl
- src/variable.jl
- test/constraint.jl
- test/extract_domain_polyopt.jl
- test/variable.jl
Updates for https://github.com/JuliaOpt/PolyJuMP.jl/pull/21
> Updates to PolyJuMP updates

- README.md
This example is long and not particularly helpful, it's better to redirect to the examples folder and the documentation. Also it does not work with CSDP
> Remove example from README

- examples/Sum-of-Squares Matrices.ipynb
- src/certificate.jl
- src/constraint.jl
- test/certificate.jl
- test/choi.jl
- test/simplematrixsos.jl
- test/sosdemo10.jl
- test/sosdemo9.jl
This is implemented in SOSTools and gives an important reduction of monomials for SOS matrix constraints (see the notebook that is added in this PR).
Related to https://github.com/JuliaOpt/SumOfSquares.jl/issues/2
> ✨ Add multipartite newton polytope computation

- REQUIRE
- src/SumOfSquares.jl
If you do `using SumOfSquares`, 99% of the time you also need to do `using JuMP` so it's probably better to do that automatically.
What do you think ?
> Reexport JuMP

- test/cosmo_tests.jl
- test/solver_tests.jl
@migarstka It works like a charm, it passes all the tests with the tolerance `1e-4` recommended in https://github.com/JuliaOpt/JuMP.jl/pull/1941
> Add COSMO to solver tests

- test/proxsdp_tests.jl
- test/solver_tests.jl
There are a few tests that fail. The horn test fail because ProxSDP gives `OPTIMIZE_NOT_CALLED` instead of ˘INFEASIBLE˘ as a termination status.
The bivariate quadratic tests fails with an error:
```
sos_bivariate_quadratic: Error During Test at /home/blegat/.julia/dev/SumOfSquares/test/Tests/utilities.jl:40
Got exception outside of a @test
BoundsError: attempt to access 6-element Array{Float64,1} at index [7:9]
Stacktrace:
[1] throw_boundserror(::Array{Float64,1}, ::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:484
[2] checkbounds at ./abstractarray.jl:449 [inlined]
[3] getindex at ./array.jl:735 [inlined]
[4] get(::ProxSDP.Optimizer, ::MathOptInterface.ConstraintDual, ::MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables,MathOptInterface.SecondOrderCone}) at …
```
> Add ProxSDP in solver tests

- test/Solvers/sdpa_family_tests.jl
Running the tests, one gets a couple of warnings due to https://github.com/ericphanson/SDPAFamily.jl/issues/22. 
I excluded three testsets which errored due to not returning the precise status required, and two that gave the error
```julia
ArgumentError: Bridge of type `MathOptInterface.Bridges.Constraint.VectorFunctionizeBridge{Float64,SumOfSquares.SOSPolynomialSet{SemialgebraicSets.FullSpace,DynamicPolynomials.Monomial{true},DynamicPolynomials.MonomialVector{true},SumOfSquares.Certificate.Remainder{SumOfSquares.NonnegPolyInnerCone{SumOfSquares.DiagonallyDominantConeTriangle},PolyJuMP.MonomialBasis,Tuple{}}}}` does not support accessing the attribute `SumOfSquares.GramMatrixAttribute(1)`.
```
but I'm not sure if that's a problem with SDPAFamily or not. The rest for the linear and SDP …
> Add SDPAFamily to tests

- .travis.yml
- test/Solvers/Manifest.toml
- test/Solvers/csdp_tests.jl
- test/options_pricing.jl
- test/sosdemo3.jl
- test/sosdemo5.jl
Reenable tests failing because of the CSDP segfaults: https://github.com/JuliaOpt/CSDP.jl/issues/39 as it was fixed in https://github.com/JuliaOpt/CSDP.jl/pull/48
> Fix CSDP segfault

- src/constraint.jl
- test/Tests/BPT12e399.jl
- test/Tests/quartic_ideal.jl
Rename `remainder` -> `newton_of_remainder` before we release.
This allows `remainder` to be used for https://github.com/JuliaOpt/SumOfSquares.jl/issues/11
> Rename remainder -> newton_of_remainder

- examples/sos_decomposition.jl
Adds a trivial SOS decomposition example in response to issue https://github.com/jump-dev/SumOfSquares.jl/issues/166#issue-645251412
It is simple but hopefully clearer than a docstring.
> Add simple SOS decomposition example

- src/Bridges/Constraint/sos_polynomial.jl
- src/Bridges/Constraint/utilities.jl
- src/sos_polynomial.jl
They could have different types for instance if some vector of monomials have small size so we can use LP or SOCP and other have large size.
This did not occur that often with VariableSparsity which is why did bug was not detect but it is now quite common with MonomialSparsity and SignSymmetry.
> Fix sparse constraints with constraint of different types

- bench/gram_to_poly.jl
- src/Bridges/Constraint/sos_polynomial.jl
- src/Bridges/Constraint/sos_polynomial_in_semialgebraic_set.jl
- src/SumOfSquares.jl
- src/sos_polynomial.jl
- src/utilities.jl
- src/variable.jl
- test/gram_matrix.jl
Before this PR, the GramMatrix was using `Float64` independently of the type of the bridge.
> Fix Gram Matrix for other types than Float64

- docs/src/variables.md
It appears the previous usage of DSOS(X) twice was a typo.
> Update SDSOS documentation

- examples/Even reduction.jl
- examples/Symmetry reduction.jl
Simple example of symmetry reduction with a group that is not a permutation groups so we need to define our own group and cannot rely on PermutationGroups.jl
> Add example of even reduction

- docs/Project.toml
- docs/src/constraints.md
- docs/src/variables.md
- examples/Dihedral symmetry of the Robinson form.jl
- examples/Even reduction.jl
- examples/Project.toml
- examples/Symmetry reduction.jl
- examples/block_diag.jl
- examples/symmetry.jl
- src/Bridges/Constraint/sos_polynomial.jl
- src/sos_polynomial.jl
For each irrep, we either have a `multiplicity` of 0 in which case we have no block or we have a nonzero multiplicities in which case, before this PR we created and SDP of size `multiplicity * degree` and after this PR we add only one PSD variable to the solver of size multiplicity and put `degree` gram matrices (all equal) in the `SparseGramMatrix`.
> Further reduce if degree of irrep is > 1

- README.md
Update the info of the JuMP-dev talk with a link to pretalkx with time, date and the slides.
Also add the upcoming presentation at POEMA
cc @kalmarek @tweisser
> Add POEMA presentation and slides for JuMP-dev

- docs/src/tutorials/Getting started/sum-of-squares_matrices.jl
- docs/src/tutorials/Noncommutative and Hermitian/noncommutative_variables.jl
- docs/src/tutorials/Noncommutative and Hermitian/sums_of_hermitian_squares.jl
I don't know where it came from. It's not defined in Literate. Maybe it came from a Search+Replace from `!jl`
> Remove !src in tutorials

- Project.toml
- docs/src/tutorials/Symmetry/dihedral_symmetry_of_the_robinson_form.jl
- docs/src/tutorials/Symmetry/even_reduction.jl
- docs/src/tutorials/Symmetry/permutation_symmetry.jl
- src/Certificate/Symmetry/wedderburn.jl
I made an update to https://github.com/kalmarek/SymbolicWedderburn.jl/pull/38. Here are the current failures even with the changes of this PR:
```jl
julia> include("src/tutorials/Symmetry/even_reduction.jl")
ERROR: LoadError: MethodError: no method matching svd!(::SparseArrays.SparseMatrixCSC{Float64, Int64})
Closest candidates are:
svd!(::LinearAlgebra.AbstractTriangular; kwargs...) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/triangular.jl:2212
svd!(::StridedMatrix{T}; full, alg) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/svd.jl:92
svd!(::StridedMatrix{T}, ::StridedMatrix{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at …
```
> Update for SymbolicWedderburn#38

- docs/src/tutorials/Polynomial Optimization/extracting_minimizers.jl
Preview https://jump-dev.github.io/SumOfSquares.jl/previews/PR271
> Add polynomial optimization example

- Project.toml
- src/constraint.jl
- test/constraint.jl
Should be consistent with the behavior of other conic sets with the new feature added in https://github.com/jump-dev/JuMP.jl/pull/3273
> Add alternative syntax for SOSCone

- docs/make.jl
- docs/src/tutorials/Symmetry/cyclic.jl
- docs/src/tutorials/Symmetry/dihedral.jl
- docs/src/tutorials/Symmetry/even_reduction.jl
- docs/src/tutorials/Symmetry/permutation_symmetry.jl
- src/Certificate/Symmetry/Symmetry.jl
- src/Certificate/Symmetry/wedderburn.jl
- src/Certificate/ideal.jl
- src/gram_matrix.jl
This was a draft a did some time ago. ~~The goal now is to wait for https://github.com/kalmarek/SymbolicWedderburn.jl/issues/79~~
Needs:
> Fix symmetry reduction

- .github/workflows/ci.yml
- docs/src/tutorials/Symmetry/cyclic.jl
- src/Bridges/Constraint/sos_polynomial_in_semialgebraic_set.jl
- src/Bridges/Variable/kernel.jl
- src/Certificate/ideal.jl
- src/Certificate/newton_polytope.jl
- src/gram_matrix.jl
> Use StarAlgebras.QuadraticForm
